-- SQL Script to Insert 50 Sample Products with Images
-- IMPORTANT: Run insert_10_categories.sql FIRST to create categories 1-10
-- Also make sure you have at least one seller (seller_id = 1) in your database
-- Products are distributed across 10 categories (5 products per category)

-- Insert Products (distributed across categories 1-10)
INSERT INTO product (title, short_description, long_description, categories_id, price, sale_price, stock_qty, calories, protein, fat, carbs, ingredients, seller_id, created_at, updated_at) VALUES
-- Category 1: Beef Sausages
('Premium Beef Sausage', 'Handcrafted premium beef sausage with traditional spices', 'Our premium beef sausage is made from the finest cuts of beef, carefully selected and prepared using traditional methods. Each sausage is handcrafted to perfection, ensuring exceptional taste and quality that has been our signature for generations.', 1, 12.99, 9.99, 150, 280.0, 18.0, 22.0, 3.0, 'Beef, salt, black pepper, garlic, natural casings', 1, NOW(), NOW()),
('Bourbon Sausage', 'Whiskey-infused premium sausage', 'A sophisticated choice infused with bourbon whiskey. This premium sausage offers complex flavors that are perfect for special occasions.', 1, 16.99, 14.99, 70, 280.0, 18.0, 21.0, 2.0, 'Beef, pork, bourbon, salt, spices, natural casings', 1, NOW(), NOW()),
('Coffee Rubbed Sausage', 'Unique coffee spice rub', 'A unique and sophisticated flavor featuring coffee spice rub. This gourmet sausage offers complex, rich flavors.', 1, 15.99, 13.99, 85, 275.0, 17.0, 21.0, 2.0, 'Beef, coffee, cocoa, spices, salt, natural casings', 1, NOW(), NOW()),
('Pepperoni Sausage', 'Classic pepperoni flavor', 'The classic pepperoni flavor you love, in sausage form. Perfect for pizza toppings, pasta dishes, or simply grilled.', 1, 12.99, 10.99, 190, 290.0, 17.0, 23.0, 3.0, 'Pork, beef, paprika, fennel, garlic, salt, natural casings', 1, NOW(), NOW()),
('Kielbasa Sausage', 'Traditional Polish kielbasa', 'Authentic Polish kielbasa made with traditional recipes. This hearty sausage is perfect for stews, soups, or simply grilled and served with mustard.', 1, 13.99, NULL, 130, 265.0, 16.0, 20.0, 2.0, 'Pork, beef, garlic, marjoram, salt, natural casings', 1, NOW(), NOW()),

-- Category 2: Pork Sausages
('Classic Pork Sausage', 'Traditional pork sausage with herbs and spices', 'A classic favorite made from premium pork, seasoned with a perfect blend of herbs and spices. This traditional recipe has been passed down through generations, delivering authentic flavor in every bite.', 2, 10.99, NULL, 200, 260.0, 16.0, 20.0, 2.0, 'Pork, salt, sage, thyme, black pepper, natural casings', 1, NOW(), NOW()),
('Spicy Italian Sausage', 'Bold and flavorful Italian-style sausage with a kick', 'Experience the bold flavors of Italy with our spicy Italian sausage. Made with premium meat and authentic Italian spices, this sausage delivers a perfect balance of heat and flavor that will awaken your taste buds.', 2, 13.99, 11.99, 120, 290.0, 17.0, 23.0, 4.0, 'Pork, fennel seeds, red pepper flakes, garlic, salt, natural casings', 1, NOW(), NOW()),
('Bratwurst Sausage', 'Authentic German bratwurst', 'Experience authentic German flavors with our traditional bratwurst. Made following time-honored German recipes, this sausage is perfect for grilling and serving with sauerkraut.', 2, 12.99, 10.99, 140, 275.0, 15.0, 22.0, 3.0, 'Pork, veal, salt, white pepper, nutmeg, natural casings', 1, NOW(), NOW()),
('Chorizo Sausage', 'Spicy Spanish-style chorizo', 'Bold and spicy, our chorizo sausage brings the vibrant flavors of Spain to your table. Made with premium meat and authentic Spanish spices, it''s perfect for paella, tapas, or grilling.', 2, 13.99, NULL, 110, 300.0, 18.0, 24.0, 4.0, 'Pork, paprika, garlic, salt, cayenne pepper, natural casings', 1, NOW(), NOW()),
('Sage Sausage', 'Traditional sage seasoning', 'A classic combination of pork and sage, this traditional sausage is perfect for stuffing, breakfast, or any meal where you want familiar, comforting flavors.', 2, 11.99, NULL, 200, 250.0, 15.0, 18.0, 2.0, 'Pork, fresh sage, salt, black pepper, natural casings', 1, NOW(), NOW()),

-- Category 3: Chicken Sausages
('Chicken Sausage', 'Lean and healthy chicken sausage option', 'A healthier alternative without compromising on taste. Our chicken sausage is made from lean chicken meat, seasoned with aromatic herbs and spices, perfect for those seeking a lighter option.', 3, 11.99, NULL, 180, 200.0, 20.0, 12.0, 2.0, 'Chicken, salt, herbs, spices, natural casings', 1, NOW(), NOW()),
('Buffalo Sausage', 'Spicy buffalo wing flavors', 'All the heat and flavor of buffalo wings in a sausage! Perfect for game day or any time you want bold, spicy flavors.', 3, 13.99, 11.99, 150, 280.0, 17.0, 21.0, 3.0, 'Chicken, buffalo sauce, blue cheese, salt, spices, natural casings', 1, NOW(), NOW()),
('Lemon Herb Sausage', 'Bright lemon with fresh herbs', 'Bright and fresh, this sausage features lemon zest and fresh herbs. Perfect for spring and summer grilling.', 3, 12.99, 10.99, 165, 240.0, 15.0, 17.0, 2.0, 'Chicken, lemon zest, dill, parsley, salt, natural casings', 1, NOW(), NOW()),
('Mango Habanero Sausage', 'Sweet mango with spicy habanero', 'A perfect balance of sweet mango and spicy habanero. This tropical-inspired sausage offers a unique flavor adventure.', 3, 14.99, NULL, 115, 280.0, 17.0, 21.0, 6.0, 'Chicken, mango, habanero, lime, salt, spices, natural casings', 1, NOW(), NOW()),
('Coconut Curry Sausage', 'Creamy coconut curry flavors', 'Creamy and aromatic, our coconut curry sausage brings the flavors of Southeast Asia to your grill. Perfect for curry lovers.', 3, 14.99, NULL, 130, 285.0, 17.0, 22.0, 5.0, 'Chicken, coconut milk, curry spices, lemongrass, salt, natural casings', 1, NOW(), NOW()),

-- Category 4: Spicy Sausages
('Bndouille Sausage', 'Spicy Cajun-style andouille', 'Bring the flavors of Louisiana to your kitchen with our spicy andouille sausage. Perfect for gumbo, jambalaya, or grilling, this sausage packs a flavorful punch.', 4, 14.99, 12.99, 90, 285.0, 17.0, 23.0, 3.0, 'Pork, garlic, cayenne pepper, salt, spices, natural casings', 1, NOW(), NOW()),
('Merguez Sausage', 'Spicy North African merguez', 'Bold and aromatic, our merguez sausage features North African spices and flavors. Perfect for grilling or adding to tagines and couscous dishes.', 4, 14.99, 13.99, 95, 295.0, 18.0, 23.0, 4.0, 'Lamb, beef, harissa, cumin, coriander, garlic, salt, natural casings', 1, NOW(), NOW()),
('Jalapeño Cheddar Sausage', 'Spicy jalapeño with creamy cheddar', 'A crowd-pleaser featuring spicy jalapeños and creamy cheddar cheese. This sausage offers a perfect balance of heat and richness.', 4, 13.99, 11.99, 125, 290.0, 17.0, 22.0, 3.0, 'Pork, jalapeños, cheddar cheese, salt, spices, natural casings', 1, NOW(), NOW()),
('Chipotle Sausage', 'Smoky chipotle with a hint of heat', 'Smoky and slightly spicy, our chipotle sausage brings Southwestern flavors to your table. Perfect for tacos, burritos, or grilling.', 4, 13.99, 11.99, 120, 275.0, 16.0, 21.0, 3.0, 'Pork, chipotle peppers, garlic, cumin, salt, natural casings', 1, NOW(), NOW()),
('Habanero Sausage', 'Extremely spicy habanero', 'For heat lovers! Our habanero sausage packs serious heat while maintaining great flavor. Not for the faint of heart.', 4, 14.99, 12.99, 95, 295.0, 18.0, 22.0, 3.0, 'Pork, habanero peppers, garlic, salt, spices, natural casings', 1, NOW(), NOW()),

-- Category 5: Breakfast Sausages
('Breakfast Sausage', 'Perfect morning sausage with maple flavor', 'Start your day right with our breakfast sausage. Infused with a hint of maple and traditional breakfast spices, this sausage pairs perfectly with eggs and pancakes.', 5, 9.99, NULL, 250, 240.0, 14.0, 18.0, 2.0, 'Pork, salt, sage, maple flavor, black pepper, natural casings', 1, NOW(), NOW()),
('Maple Bacon Sausage', 'Sweet maple with smoky bacon', 'The perfect combination of sweet maple and smoky bacon flavors. This indulgent sausage is a breakfast favorite.', 5, 14.99, 12.99, 145, 300.0, 17.0, 23.0, 4.0, 'Pork, bacon, maple syrup, salt, spices, natural casings', 1, NOW(), NOW()),
('Apple Cider Sausage', 'Sweet and savory apple cider infused', 'A unique combination of sweet and savory, our apple cider sausage is infused with fresh apple cider and warm spices. Perfect for autumn meals.', 5, 12.99, 10.99, 115, 250.0, 15.0, 19.0, 5.0, 'Pork, apple cider, cinnamon, nutmeg, salt, natural casings', 1, NOW(), NOW()),
('Honey Mustard Sausage', 'Sweet and tangy honey mustard flavor', 'A delightful combination of sweet honey and tangy mustard, this sausage offers a unique flavor profile that pairs well with many dishes.', 5, 11.99, NULL, 160, 245.0, 16.0, 18.0, 4.0, 'Pork, honey, mustard, salt, spices, natural casings', 1, NOW(), NOW()),
('Bacon Wrapped Sausage', 'Sausage wrapped in premium bacon', 'The ultimate indulgence - our premium sausage wrapped in crispy bacon. Double the flavor, double the satisfaction.', 5, 16.99, 14.99, 90, 350.0, 19.0, 28.0, 2.0, 'Pork, bacon, salt, spices, natural casings', 1, NOW(), NOW()),

-- Category 6: Gourmet Sausages
('Gourmet Lamb Sausage', 'Premium lamb sausage with Mediterranean flavors', 'Indulge in the rich, distinctive flavor of our gourmet lamb sausage. Infused with Mediterranean herbs and spices, this premium sausage offers a sophisticated taste experience.', 6, 15.99, 13.99, 80, 310.0, 19.0, 24.0, 3.0, 'Lamb, rosemary, garlic, mint, salt, natural casings', 1, NOW(), NOW()),
('Black Truffle Sausage', 'Luxurious black truffle', 'The ultimate luxury sausage featuring black truffle. This premium option is perfect for special occasions and gourmet dining.', 6, 24.99, 21.99, 50, 290.0, 18.0, 22.0, 2.0, 'Pork, black truffle, salt, white pepper, natural casings', 1, NOW(), NOW()),
('Duck Sausage', 'Rich and flavorful duck', 'Rich and flavorful duck sausage with a sophisticated taste. A gourmet choice for special occasions and fine dining at home.', 6, 17.99, 15.99, 65, 320.0, 20.0, 25.0, 2.0, 'Duck, orange, thyme, salt, black pepper, natural casings', 1, NOW(), NOW()),
('Balsamic Fig Sausage', 'Sweet figs with balsamic', 'A gourmet combination of sweet figs and tangy balsamic vinegar. This sophisticated sausage is perfect for pairing with cheese and wine.', 6, 15.99, 13.99, 80, 270.0, 17.0, 20.0, 5.0, 'Pork, figs, balsamic vinegar, rosemary, salt, natural casings', 1, NOW(), NOW()),
('Rosemary Lamb Sausage', 'Fresh rosemary with premium lamb', 'Premium lamb paired with fresh rosemary creates an elegant and aromatic sausage. Perfect for special dinners and entertaining.', 6, 16.99, 14.99, 75, 305.0, 19.0, 24.0, 2.0, 'Lamb, fresh rosemary, garlic, salt, black pepper, natural casings', 1, NOW(), NOW()),

-- Category 7: Smoked Sausages
('Smoked Sausage', 'Traditional smoked sausage with deep flavor', 'Slow-smoked to perfection, our smoked sausage offers a deep, rich flavor that comes from hours of careful smoking. The perfect choice for grilling and barbecuing.', 7, 14.99, 12.99, 100, 270.0, 16.0, 21.0, 3.0, 'Pork, beef, salt, spices, natural smoke flavor, natural casings', 1, NOW(), NOW()),
('BBQ Sausage', 'Classic barbecue flavors', 'Smoky and sweet, our BBQ sausage is perfect for grilling and barbecuing. Coated with our signature barbecue spice blend.', 7, 12.99, 10.99, 180, 270.0, 16.0, 20.0, 4.0, 'Pork, BBQ spices, brown sugar, salt, natural casings', 1, NOW(), NOW()),
('Chipotle Lime Sausage', 'Smoky chipotle with fresh lime', 'Smoky chipotle meets fresh lime in this zesty sausage. Perfect for tacos, burritos, or any Mexican-inspired dish.', 7, 13.99, NULL, 160, 265.0, 16.0, 20.0, 3.0, 'Pork, chipotle, lime zest, cilantro, salt, natural casings', 1, NOW(), NOW()),
('Cajun Spice Sausage', 'Bold Cajun seasoning blend', 'Bold and flavorful, our Cajun spice sausage features a perfect blend of Cajun seasonings. Great for jambalaya, gumbo, or grilling.', 7, 13.99, NULL, 130, 285.0, 17.0, 22.0, 3.0, 'Pork, Cajun spices, garlic, paprika, salt, natural casings', 1, NOW(), NOW()),
('Honey Sriracha Sausage', 'Sweet honey with spicy sriracha', 'The perfect balance of sweet honey and spicy sriracha. This crowd-pleasing sausage offers addictive flavors.', 7, 13.99, 11.99, 175, 270.0, 16.0, 20.0, 4.0, 'Pork, honey, sriracha, garlic, salt, natural casings', 1, NOW(), NOW()),

-- Category 8: International Sausages
('Beer Brat Sausage', 'Beer-infused bratwurst', 'Our bratwurst is infused with premium beer, adding depth and complexity to the traditional German flavors. Perfect for beer gardens and cookouts.', 8, 13.99, 11.99, 140, 265.0, 15.0, 21.0, 2.0, 'Pork, beer, salt, white pepper, caraway seeds, natural casings', 1, NOW(), NOW()),
('Thai Curry Sausage', 'Exotic Thai curry flavors', 'Experience the exotic flavors of Thailand with our Thai curry sausage. Featuring authentic Thai spices and herbs.', 8, 14.99, 12.99, 110, 275.0, 17.0, 20.0, 4.0, 'Pork, Thai curry paste, coconut, lemongrass, salt, natural casings', 1, NOW(), NOW()),
('Pineapple Teriyaki Sausage', 'Sweet and savory Asian-inspired', 'A fusion of sweet pineapple and savory teriyaki flavors. This unique sausage brings Asian-inspired tastes to your grill.', 8, 13.99, NULL, 125, 260.0, 16.0, 19.0, 5.0, 'Pork, pineapple, teriyaki sauce, ginger, garlic, salt, natural casings', 1, NOW(), NOW()),
('Ginger Soy Sausage', 'Asian-inspired ginger soy', 'Asian flavors come together in this ginger soy sausage. Perfect for stir-fries, ramen, or grilling with Asian vegetables.', 8, 13.99, 11.99, 145, 255.0, 16.0, 19.0, 4.0, 'Pork, ginger, soy sauce, garlic, sesame, salt, natural casings', 1, NOW(), NOW()),
('Wasabi Sausage', 'Spicy Japanese wasabi', 'Bold and unique, our wasabi sausage brings Japanese heat to your table. Perfect for those who love intense, clean heat.', 8, 14.99, 12.99, 100, 265.0, 17.0, 20.0, 2.0, 'Pork, wasabi, soy sauce, ginger, salt, natural casings', 1, NOW(), NOW()),

-- Category 9: Specialty Sausages
('Sun-Dried Tomato Sausage', 'Mediterranean flavors with sun-dried tomatoes', 'Inspired by Mediterranean cuisine, this sausage features sun-dried tomatoes and Italian herbs. Perfect for pasta dishes or grilling.', 9, 13.99, NULL, 135, 260.0, 16.0, 20.0, 3.0, 'Pork, sun-dried tomatoes, basil, oregano, garlic, salt, natural casings', 1, NOW(), NOW()),
('Feta and Olive Sausage', 'Greek-inspired with feta and olives', 'Mediterranean flavors come together in this unique sausage featuring feta cheese and olives. A perfect addition to Greek-inspired meals.', 9, 14.99, NULL, 105, 270.0, 17.0, 20.0, 3.0, 'Lamb, feta cheese, kalamata olives, oregano, garlic, salt, natural casings', 1, NOW(), NOW()),
('Wild Mushroom Sausage', 'Earthy wild mushroom flavors', 'Earthy and savory, this sausage features wild mushrooms and herbs. A gourmet choice for those who appreciate complex, umami-rich flavors.', 9, 15.99, 13.99, 85, 240.0, 16.0, 17.0, 2.0, 'Pork, wild mushrooms, thyme, garlic, salt, natural casings', 1, NOW(), NOW()),
('Portobello Mushroom Sausage', 'Earthy portobello mushrooms', 'Rich and earthy portobello mushrooms are the star of this gourmet sausage. Perfect for vegetarian-friendly flavor in a meat sausage.', 9, 14.99, 12.99, 105, 235.0, 15.0, 16.0, 2.0, 'Pork, portobello mushrooms, thyme, garlic, salt, natural casings', 1, NOW(), NOW()),
('Pesto Sausage', 'Fresh basil pesto flavors', 'Fresh basil pesto is mixed into this aromatic sausage. Bring the flavors of Italy to your grill with this delicious option.', 9, 13.99, 11.99, 135, 260.0, 16.0, 19.0, 3.0, 'Pork, basil, pine nuts, parmesan, garlic, olive oil, salt, natural casings', 1, NOW(), NOW()),

-- Category 10: Organic Sausages
('Turkey Sausage', 'Lean turkey sausage with herbs', 'A lean and healthy option made from premium turkey meat. Seasoned with aromatic herbs, this sausage offers great taste with fewer calories.', 10, 10.99, 8.99, 170, 180.0, 22.0, 8.0, 1.0, 'Turkey, salt, herbs, spices, natural casings', 1, NOW(), NOW()),
('Venison Sausage', 'Game sausage with wild flavors', 'For the adventurous palate, our venison sausage offers rich, gamey flavors. Made from premium venison and carefully selected spices.', 10, 18.99, 16.99, 60, 220.0, 25.0, 12.0, 1.0, 'Venison, pork fat, salt, juniper berries, black pepper, natural casings', 1, NOW(), NOW()),
('Wild Boar Sausage', 'Gamey wild boar flavors', 'For the adventurous eater, our wild boar sausage offers rich, gamey flavors. A premium choice for special occasions.', 10, 19.99, 17.99, 55, 240.0, 24.0, 14.0, 1.0, 'Wild boar, juniper berries, garlic, salt, natural casings', 1, NOW(), NOW()),
('Garlic Herb Sausage', 'Aromatic garlic and fresh herbs', 'Packed with fresh garlic and aromatic herbs, this sausage delivers bold flavors that enhance any meal. Perfect for grilling or pan-frying.', 10, 12.99, 10.99, 175, 255.0, 16.0, 19.0, 2.0, 'Pork, fresh garlic, rosemary, thyme, parsley, salt, natural casings', 1, NOW(), NOW()),
('Herb de Provence Sausage', 'French herbs and spices', 'Elegant French flavors with a blend of herbs de Provence. This sophisticated sausage brings the taste of the French countryside to your table.', 10, 14.99, 12.99, 100, 255.0, 16.0, 19.0, 2.0, 'Pork, herbs de Provence, garlic, salt, natural casings', 1, NOW(), NOW()),
('Caramelized Onion Sausage', 'Sweet caramelized onions', 'Sweet and savory caramelized onions are mixed into this delicious sausage. Perfect for adding depth to any meal.', 10, 13.99, NULL, 155, 255.0, 16.0, 19.0, 4.0, 'Pork, caramelized onions, thyme, salt, natural casings', 1, NOW(), NOW()),
('Cranberry Sausage', 'Festive cranberry flavor', 'A festive favorite featuring sweet and tart cranberries. Perfect for holiday meals and special occasions.', 10, 13.99, 11.99, 140, 245.0, 15.0, 18.0, 6.0, 'Turkey, cranberries, orange zest, sage, salt, natural casings', 1, NOW(), NOW()),
('Ratatouille Sausage', 'Mediterranean vegetable blend', 'Inspired by the classic French dish, this sausage features Mediterranean vegetables and herbs. A vegetarian-friendly flavor profile in a meat sausage.', 10, 14.99, NULL, 120, 250.0, 15.0, 18.0, 4.0, 'Pork, eggplant, zucchini, bell peppers, tomatoes, herbs, salt, natural casings', 1, NOW(), NOW()),
('Andouille Sausage', 'Spicy Cajun-style andouille', 'Bring the flavors of Louisiana to your kitchen with our spicy andouille sausage. Perfect for gumbo, jambalaya, or grilling, this sausage packs a flavorful punch.', 1, 14.99, 12.99, 90, 285.0, 17.0, 23.0, 3.0, 'Pork, garlic, cayenne pepper, salt, spices, natural casings', 1, NOW(), NOW()),
('Kielbasa Sausage', 'Traditional Polish kielbasa', 'Authentic Polish kielbasa made with traditional recipes. This hearty sausage is perfect for stews, soups, or simply grilled and served with mustard.', 1, 13.99, NULL, 130, 265.0, 16.0, 20.0, 2.0, 'Pork, beef, garlic, marjoram, salt, natural casings', 1, NOW(), NOW()),
('Merguez Sausage', 'Spicy North African merguez', 'Bold and aromatic, our merguez sausage features North African spices and flavors. Perfect for grilling or adding to tagines and couscous dishes.', 1, 14.99, 13.99, 95, 295.0, 18.0, 23.0, 4.0, 'Lamb, beef, harissa, cumin, coriander, garlic, salt, natural casings', 1, NOW(), NOW()),
('Venison Sausage', 'Game sausage with wild flavors', 'For the adventurous palate, our venison sausage offers rich, gamey flavors. Made from premium venison and carefully selected spices.', 1, 18.99, 16.99, 60, 220.0, 25.0, 12.0, 1.0, 'Venison, pork fat, salt, juniper berries, black pepper, natural casings', 1, NOW(), NOW()),
('Apple Cider Sausage', 'Sweet and savory apple cider infused', 'A unique combination of sweet and savory, our apple cider sausage is infused with fresh apple cider and warm spices. Perfect for autumn meals.', 1, 12.99, 10.99, 115, 250.0, 15.0, 19.0, 5.0, 'Pork, apple cider, cinnamon, nutmeg, salt, natural casings', 1, NOW(), NOW()),
('Honey Mustard Sausage', 'Sweet and tangy honey mustard flavor', 'A delightful combination of sweet honey and tangy mustard, this sausage offers a unique flavor profile that pairs well with many dishes.', 1, 11.99, NULL, 160, 245.0, 16.0, 18.0, 4.0, 'Pork, honey, mustard, salt, spices, natural casings', 1, NOW(), NOW()),
('Garlic Herb Sausage', 'Aromatic garlic and fresh herbs', 'Packed with fresh garlic and aromatic herbs, this sausage delivers bold flavors that enhance any meal. Perfect for grilling or pan-frying.', 1, 12.99, 10.99, 175, 255.0, 16.0, 19.0, 2.0, 'Pork, fresh garlic, rosemary, thyme, parsley, salt, natural casings', 1, NOW(), NOW()),
('Jalapeño Cheddar Sausage', 'Spicy jalapeño with creamy cheddar', 'A crowd-pleaser featuring spicy jalapeños and creamy cheddar cheese. This sausage offers a perfect balance of heat and richness.', 1, 13.99, 11.99, 125, 290.0, 17.0, 22.0, 3.0, 'Pork, jalapeños, cheddar cheese, salt, spices, natural casings', 1, NOW(), NOW()),
('Bourbon Sausage', 'Whiskey-infused premium sausage', 'A sophisticated choice infused with bourbon whiskey. This premium sausage offers complex flavors that are perfect for special occasions.', 1, 16.99, 14.99, 70, 280.0, 18.0, 21.0, 2.0, 'Beef, pork, bourbon, salt, spices, natural casings', 1, NOW(), NOW()),
('Sun-Dried Tomato Sausage', 'Mediterranean flavors with sun-dried tomatoes', 'Inspired by Mediterranean cuisine, this sausage features sun-dried tomatoes and Italian herbs. Perfect for pasta dishes or grilling.', 1, 13.99, NULL, 135, 260.0, 16.0, 20.0, 3.0, 'Pork, sun-dried tomatoes, basil, oregano, garlic, salt, natural casings', 1, NOW(), NOW()),
('Maple Bacon Sausage', 'Sweet maple with smoky bacon', 'The perfect combination of sweet maple and smoky bacon flavors. This indulgent sausage is a breakfast favorite.', 1, 14.99, 12.99, 145, 300.0, 17.0, 23.0, 4.0, 'Pork, bacon, maple syrup, salt, spices, natural casings', 1, NOW(), NOW()),
('Chipotle Sausage', 'Smoky chipotle with a hint of heat', 'Smoky and slightly spicy, our chipotle sausage brings Southwestern flavors to your table. Perfect for tacos, burritos, or grilling.', 1, 13.99, 11.99, 120, 275.0, 16.0, 21.0, 3.0, 'Pork, chipotle peppers, garlic, cumin, salt, natural casings', 1, NOW(), NOW()),
('Feta and Olive Sausage', 'Greek-inspired with feta and olives', 'Mediterranean flavors come together in this unique sausage featuring feta cheese and olives. A perfect addition to Greek-inspired meals.', 1, 14.99, NULL, 105, 270.0, 17.0, 20.0, 3.0, 'Lamb, feta cheese, kalamata olives, oregano, garlic, salt, natural casings', 1, NOW(), NOW()),
('Beer Brat Sausage', 'Beer-infused bratwurst', 'Our bratwurst is infused with premium beer, adding depth and complexity to the traditional German flavors. Perfect for beer gardens and cookouts.', 1, 13.99, 11.99, 140, 265.0, 15.0, 21.0, 2.0, 'Pork, beer, salt, white pepper, caraway seeds, natural casings', 1, NOW(), NOW()),
('Wild Mushroom Sausage', 'Earthy wild mushroom flavors', 'Earthy and savory, this sausage features wild mushrooms and herbs. A gourmet choice for those who appreciate complex, umami-rich flavors.', 1, 15.99, 13.99, 85, 240.0, 16.0, 17.0, 2.0, 'Pork, wild mushrooms, thyme, garlic, salt, natural casings', 1, NOW(), NOW()),
('Cajun Spice Sausage', 'Bold Cajun seasoning blend', 'Bold and flavorful, our Cajun spice sausage features a perfect blend of Cajun seasonings. Great for jambalaya, gumbo, or grilling.', 1, 13.99, NULL, 130, 285.0, 17.0, 22.0, 3.0, 'Pork, Cajun spices, garlic, paprika, salt, natural casings', 1, NOW(), NOW()),
('Herb de Provence Sausage', 'French herbs and spices', 'Elegant French flavors with a blend of herbs de Provence. This sophisticated sausage brings the taste of the French countryside to your table.', 1, 14.99, 12.99, 100, 255.0, 16.0, 19.0, 2.0, 'Pork, herbs de Provence, garlic, salt, natural casings', 1, NOW(), NOW()),
('BBQ Sausage', 'Classic barbecue flavors', 'Smoky and sweet, our BBQ sausage is perfect for grilling and barbecuing. Coated with our signature barbecue spice blend.', 1, 12.99, 10.99, 180, 270.0, 16.0, 20.0, 4.0, 'Pork, BBQ spices, brown sugar, salt, natural casings', 1, NOW(), NOW()),
('Pineapple Teriyaki Sausage', 'Sweet and savory Asian-inspired', 'A fusion of sweet pineapple and savory teriyaki flavors. This unique sausage brings Asian-inspired tastes to your grill.', 1, 13.99, NULL, 125, 260.0, 16.0, 19.0, 5.0, 'Pork, pineapple, teriyaki sauce, ginger, garlic, salt, natural casings', 1, NOW(), NOW()),
('Rosemary Lamb Sausage', 'Fresh rosemary with premium lamb', 'Premium lamb paired with fresh rosemary creates an elegant and aromatic sausage. Perfect for special dinners and entertaining.', 1, 16.99, 14.99, 75, 305.0, 19.0, 24.0, 2.0, 'Lamb, fresh rosemary, garlic, salt, black pepper, natural casings', 1, NOW(), NOW()),
('Buffalo Sausage', 'Spicy buffalo wing flavors', 'All the heat and flavor of buffalo wings in a sausage! Perfect for game day or any time you want bold, spicy flavors.', 1, 13.99, 11.99, 150, 280.0, 17.0, 21.0, 3.0, 'Chicken, buffalo sauce, blue cheese, salt, spices, natural casings', 1, NOW(), NOW()),
('Sage Sausage', 'Traditional sage seasoning', 'A classic combination of pork and sage, this traditional sausage is perfect for stuffing, breakfast, or any meal where you want familiar, comforting flavors.', 1, 11.99, NULL, 200, 250.0, 15.0, 18.0, 2.0, 'Pork, fresh sage, salt, black pepper, natural casings', 1, NOW(), NOW()),
('Thai Curry Sausage', 'Exotic Thai curry flavors', 'Experience the exotic flavors of Thailand with our Thai curry sausage. Featuring authentic Thai spices and herbs.', 1, 14.99, 12.99, 110, 275.0, 17.0, 20.0, 4.0, 'Pork, Thai curry paste, coconut, lemongrass, salt, natural casings', 1, NOW(), NOW()),
('Pepperoni Sausage', 'Classic pepperoni flavor', 'The classic pepperoni flavor you love, in sausage form. Perfect for pizza toppings, pasta dishes, or simply grilled.', 1, 12.99, 10.99, 190, 290.0, 17.0, 23.0, 3.0, 'Pork, beef, paprika, fennel, garlic, salt, natural casings', 1, NOW(), NOW()),
('Caramelized Onion Sausage', 'Sweet caramelized onions', 'Sweet and savory caramelized onions are mixed into this delicious sausage. Perfect for adding depth to any meal.', 1, 13.99, NULL, 155, 255.0, 16.0, 19.0, 4.0, 'Pork, caramelized onions, thyme, salt, natural casings', 1, NOW(), NOW()),
('Cranberry Sausage', 'Festive cranberry flavor', 'A festive favorite featuring sweet and tart cranberries. Perfect for holiday meals and special occasions.', 1, 13.99, 11.99, 140, 245.0, 15.0, 18.0, 6.0, 'Turkey, cranberries, orange zest, sage, salt, natural casings', 1, NOW(), NOW()),
('Habanero Sausage', 'Extremely spicy habanero', 'For heat lovers! Our habanero sausage packs serious heat while maintaining great flavor. Not for the faint of heart.', 1, 14.99, 12.99, 95, 295.0, 18.0, 22.0, 3.0, 'Pork, habanero peppers, garlic, salt, spices, natural casings', 1, NOW(), NOW()),
('Duck Sausage', 'Rich and flavorful duck', 'Rich and flavorful duck sausage with a sophisticated taste. A gourmet choice for special occasions and fine dining at home.', 1, 17.99, 15.99, 65, 320.0, 20.0, 25.0, 2.0, 'Duck, orange, thyme, salt, black pepper, natural casings', 1, NOW(), NOW()),
('Balsamic Fig Sausage', 'Sweet figs with balsamic', 'A gourmet combination of sweet figs and tangy balsamic vinegar. This sophisticated sausage is perfect for pairing with cheese and wine.', 1, 15.99, 13.99, 80, 270.0, 17.0, 20.0, 5.0, 'Pork, figs, balsamic vinegar, rosemary, salt, natural casings', 1, NOW(), NOW()),
('Pesto Sausage', 'Fresh basil pesto flavors', 'Fresh basil pesto is mixed into this aromatic sausage. Bring the flavors of Italy to your grill with this delicious option.', 1, 13.99, 11.99, 135, 260.0, 16.0, 19.0, 3.0, 'Pork, basil, pine nuts, parmesan, garlic, olive oil, salt, natural casings', 1, NOW(), NOW()),
('Mango Habanero Sausage', 'Sweet mango with spicy habanero', 'A perfect balance of sweet mango and spicy habanero. This tropical-inspired sausage offers a unique flavor adventure.', 1, 14.99, NULL, 115, 280.0, 17.0, 21.0, 6.0, 'Chicken, mango, habanero, lime, salt, spices, natural casings', 1, NOW(), NOW()),
('Black Truffle Sausage', 'Luxurious black truffle', 'The ultimate luxury sausage featuring black truffle. This premium option is perfect for special occasions and gourmet dining.', 1, 24.99, 21.99, 50, 290.0, 18.0, 22.0, 2.0, 'Pork, black truffle, salt, white pepper, natural casings', 1, NOW(), NOW()),
('Ginger Soy Sausage', 'Asian-inspired ginger soy', 'Asian flavors come together in this ginger soy sausage. Perfect for stir-fries, ramen, or grilling with Asian vegetables.', 1, 13.99, 11.99, 145, 255.0, 16.0, 19.0, 4.0, 'Pork, ginger, soy sauce, garlic, sesame, salt, natural casings', 1, NOW(), NOW()),
('Ratatouille Sausage', 'Mediterranean vegetable blend', 'Inspired by the classic French dish, this sausage features Mediterranean vegetables and herbs. A vegetarian-friendly flavor profile in a meat sausage.', 1, 14.99, NULL, 120, 250.0, 15.0, 18.0, 4.0, 'Pork, eggplant, zucchini, bell peppers, tomatoes, herbs, salt, natural casings', 1, NOW(), NOW()),
('Wasabi Sausage', 'Spicy Japanese wasabi', 'Bold and unique, our wasabi sausage brings Japanese heat to your table. Perfect for those who love intense, clean heat.', 1, 14.99, 12.99, 100, 265.0, 17.0, 20.0, 2.0, 'Pork, wasabi, soy sauce, ginger, salt, natural casings', 1, NOW(), NOW()),
('Bacon Wrapped Sausage', 'Sausage wrapped in premium bacon', 'The ultimate indulgence - our premium sausage wrapped in crispy bacon. Double the flavor, double the satisfaction.', 1, 16.99, 14.99, 90, 350.0, 19.0, 28.0, 2.0, 'Pork, bacon, salt, spices, natural casings', 1, NOW(), NOW()),
('Lemon Herb Sausage', 'Bright lemon with fresh herbs', 'Bright and fresh, this sausage features lemon zest and fresh herbs. Perfect for spring and summer grilling.', 1, 12.99, 10.99, 165, 240.0, 15.0, 17.0, 2.0, 'Chicken, lemon zest, dill, parsley, salt, natural casings', 1, NOW(), NOW()),
('Coffee Rubbed Sausage', 'Unique coffee spice rub', 'A unique and sophisticated flavor featuring coffee spice rub. This gourmet sausage offers complex, rich flavors.', 1, 15.99, 13.99, 85, 275.0, 17.0, 21.0, 2.0, 'Beef, coffee, cocoa, spices, salt, natural casings', 1, NOW(), NOW()),
('Coconut Curry Sausage', 'Creamy coconut curry flavors', 'Creamy and aromatic, our coconut curry sausage brings the flavors of Southeast Asia to your grill. Perfect for curry lovers.', 1, 14.99, NULL, 130, 285.0, 17.0, 22.0, 5.0, 'Chicken, coconut milk, curry spices, lemongrass, salt, natural casings', 1, NOW(), NOW()),
('Honey Sriracha Sausage', 'Sweet honey with spicy sriracha', 'The perfect balance of sweet honey and spicy sriracha. This crowd-pleasing sausage offers addictive flavors.', 1, 13.99, 11.99, 175, 270.0, 16.0, 20.0, 4.0, 'Pork, honey, sriracha, garlic, salt, natural casings', 1, NOW(), NOW()),
('Wild Boar Sausage', 'Gamey wild boar flavors', 'For the adventurous eater, our wild boar sausage offers rich, gamey flavors. A premium choice for special occasions.', 1, 19.99, 17.99, 55, 240.0, 24.0, 14.0, 1.0, 'Wild boar, juniper berries, garlic, salt, natural casings', 1, NOW(), NOW()),
('Chipotle Lime Sausage', 'Smoky chipotle with fresh lime', 'Smoky chipotle meets fresh lime in this zesty sausage. Perfect for tacos, burritos, or any Mexican-inspired dish.', 1, 13.99, NULL, 160, 265.0, 16.0, 20.0, 3.0, 'Pork, chipotle, lime zest, cilantro, salt, natural casings', 1, NOW(), NOW()),
('Portobello Mushroom Sausage', 'Earthy portobello mushrooms', 'Rich and earthy portobello mushrooms are the star of this gourmet sausage. Perfect for vegetarian-friendly flavor in a meat sausage.', 1, 14.99, 12.99, 105, 235.0, 15.0, 16.0, 2.0, 'Pork, portobello mushrooms, thyme, garlic, salt, natural casings', 1, NOW(), NOW());

-- Insert Product Images (Sample images - adjust paths according to your setup)
-- Note: These are placeholder image URLs. Replace with actual image paths or URLs
INSERT INTO product_image (product_id, image) VALUES
(1, '/uploads/product/1/sample-sausage-1.jpg'),
(2, '/uploads/product/2/sample-sausage-2.jpg'),
(3, '/uploads/product/3/sample-sausage-3.jpg'),
(4, '/uploads/product/4/sample-sausage-4.jpg'),
(5, '/uploads/product/5/sample-sausage-5.jpg'),
(6, '/uploads/product/6/sample-sausage-6.jpg'),
(7, '/uploads/product/7/sample-sausage-7.jpg'),
(8, '/uploads/product/8/sample-sausage-8.jpg'),
(9, '/uploads/product/9/sample-sausage-9.jpg'),
(10, '/uploads/product/10/sample-sausage-10.jpg'),
(11, '/uploads/product/11/sample-sausage-11.jpg'),
(12, '/uploads/product/12/sample-sausage-12.jpg'),
(13, '/uploads/product/13/sample-sausage-13.jpg'),
(14, '/uploads/product/14/sample-sausage-14.jpg'),
(15, '/uploads/product/15/sample-sausage-15.jpg'),
(16, '/uploads/product/16/sample-sausage-16.jpg'),
(17, '/uploads/product/17/sample-sausage-17.jpg'),
(18, '/uploads/product/18/sample-sausage-18.jpg'),
(19, '/uploads/product/19/sample-sausage-19.jpg'),
(20, '/uploads/product/20/sample-sausage-20.jpg'),
(21, '/uploads/product/21/sample-sausage-21.jpg'),
(22, '/uploads/product/22/sample-sausage-22.jpg'),
(23, '/uploads/product/23/sample-sausage-23.jpg'),
(24, '/uploads/product/24/sample-sausage-24.jpg'),
(25, '/uploads/product/25/sample-sausage-25.jpg'),
(26, '/uploads/product/26/sample-sausage-26.jpg'),
(27, '/uploads/product/27/sample-sausage-27.jpg'),
(28, '/uploads/product/28/sample-sausage-28.jpg'),
(29, '/uploads/product/29/sample-sausage-29.jpg'),
(30, '/uploads/product/30/sample-sausage-30.jpg'),
(31, '/uploads/product/31/sample-sausage-31.jpg'),
(32, '/uploads/product/32/sample-sausage-32.jpg'),
(33, '/uploads/product/33/sample-sausage-33.jpg'),
(34, '/uploads/product/34/sample-sausage-34.jpg'),
(35, '/uploads/product/35/sample-sausage-35.jpg'),
(36, '/uploads/product/36/sample-sausage-36.jpg'),
(37, '/uploads/product/37/sample-sausage-37.jpg'),
(38, '/uploads/product/38/sample-sausage-38.jpg'),
(39, '/uploads/product/39/sample-sausage-39.jpg'),
(40, '/uploads/product/40/sample-sausage-40.jpg'),
(41, '/uploads/product/41/sample-sausage-41.jpg'),
(42, '/uploads/product/42/sample-sausage-42.jpg'),
(43, '/uploads/product/43/sample-sausage-43.jpg'),
(44, '/uploads/product/44/sample-sausage-44.jpg'),
(45, '/uploads/product/45/sample-sausage-45.jpg'),
(46, '/uploads/product/46/sample-sausage-46.jpg'),
(47, '/uploads/product/47/sample-sausage-47.jpg'),
(48, '/uploads/product/48/sample-sausage-48.jpg'),
(49, '/uploads/product/49/sample-sausage-49.jpg'),
(50, '/uploads/product/50/sample-sausage-50.jpg');

